services:
  resume-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env.production
    volumes:
      - ./src:/usr/src/apps/resume/src
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
    networks:
      - resume-backend
  postgres:
    container_name: postgres_db
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}  # 设置用户名
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  # 设置密码
      - POSTGRES_DB=${POSTGRES_DB}  # 初始化时创建的数据库名
    ports:
      - "5432:5432"  # 映射到本地5432端口
    volumes:
      - postgres_data:/var/lib/postgresql/data  # 持久化数据到本地
    networks:
      - resume-backend
  
  redis:
    container_name: redis_db
    image: redis:5.0
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - resume-backend

volumes:
  postgres_data:
  redis_data:

networks:
  resume-backend:
    